server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: password
  application:
    name: user-service
  config:
    activate:
      on-profile: dev
